name: Windows Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: out/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
      - name: "Setup Microsoft build"
        uses: microsoft/setup-msbuild@v1.0.3
      - name: "Setup MSVC development tools"
        uses: ilammy/msvc-dev-cmd@v1
      - name: Generate ninja project
        run: cmake -S . -B "out" -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="Release"
      - name: Build
        run: cmake --build "out"
      - name: Run Tests
        run: ctest --test-dir "out" -VV